project:
  type: website
  output-dir: docs

website:
  title: "Practice-Matplotlib"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - note/part_01.qmd
      - note/part_02.qmd
      - tutorial/Hands-On_01.ipynb
      - tutorial/Hands-On_02.ipynb
      - tutorial/Hands-On_03.ipynb


bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  # pdf:
  #   documentclass: scrreprt
  #   papersize: a4
  #   toc: true
  #   toc-depth: 2
  #   number-sections: true
  #   colorlinks: true
  #   include-in-header: 
  #     text: |
  #       \usepackage{kotex}
